### ISSUE TITLE
which version node & npm used in project ?

### ISSUE THREAD

**Issue by todokku** [ReinanHS/tiktok-ui#1]
Hi Reinan,
which version node & npm used in project ?

**Comment by ReinanHS** [comment]
Hello, the versions of my development environment are listed below: 
- Binaries:
    - Node: 12.14.0
    - Yarn: 1.21.1
    - npm: 6.13.6
- npmPackages:
    - react: 16.9.0
    - react-native: 0.61.5
- SDKs:
   - Android SDK:
     - API Levels: 26, 28, 29
     - Build Tools: 26.0.3, 28.0.3, 29.0.2
     - System Images: android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86
